apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-1lq1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-1lq1
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-1lq1
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-1lq1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-1lq1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ipmp-tenant/rhtap-demo-app/hacbs-test-project-1lq1@sha256:baeb0ac3c24a969e85dc4c3a64cc72440047c8ff53c7021a6f58ba2b04a51d81
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
